/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

// #import <FBSDKCoreKit/FBSDKCoreKit.h>
// #import <FBSDKLoginKit/FBSDKLoginKit.h>
#import "AppDelegate.h"

#import "RCTRootView.h"
#import "CodePush.h"
#import "RCTLog.h"
 
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  RCTSetLogThreshold(RCTLogLevelInfo);
  //NSURL *jsCodeLocation;

//  NSString *jsBundleUrlString;
//  
//  if (TARGET_IPHONE_SIMULATOR) {
//    jsBundleUrlString = @"http://localhost:8081/index.ios.bundle?platform=ios&dev=false";
//  } else {
//    NSString *serverIP = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"SERVER_IP"];
//    NSString *jsCodeUrlString = [NSString stringWithFormat:@"http://%@:8081/index.ios.bundle", serverIP];
//    jsBundleUrlString = [jsCodeUrlString stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
//  }
//  
  //jsCodeLocation = [NSURL URLWithString:jsBundleUrlString];

  //[[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];

  /**
   * Loading JavaScript code - uncomment the one you want.
   *
   * OPTION 1
   * Load from development server. Start the server from the repository root:
   *
   * $ npm start
   *
   * To run on device, change `localhost` to the IP address of your computer
   * (you can get this by typing `ifconfig` into the terminal and selecting the
   * `inet` value under `en0:`) and make sure your computer and iOS device are
   * on the same Wi-Fi network.
   */

  // http://moduscreate.com/automated-ip-configuration-for-react-native-development/
  // generate https://github.com/facebook/react-native/issues/240#issuecomment-86977126

  /**
   * OPTION 2
   * Load from pre-bundled file on disk. The static bundle is automatically
   * generated by "Bundle React Native code and images" build step.
   */

//   jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];

  NSURL *jsCodeLocation;
  
  jsCodeLocation = [CodePush bundleURL];


    NSLog(@"bundle URL: %@", [jsCodeLocation absoluteString]);
//  NSString *jsBundleUrlString;
//  
//  if (TARGET_IPHONE_SIMULATOR) {
//    jsBundleUrlString = @"http://localhost:8081/index.ios.bundle?platform=ios&dev=false";
//  } else {
//    NSString *serverIP = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"SERVER_IP"];
//    NSString *jsCodeUrlString = [NSString stringWithFormat:@"http://%@:8081/index.ios.bundle", serverIP];
//    jsBundleUrlString = [jsCodeUrlString stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
//  }
//  jsCodeLocation = [NSURL URLWithString:jsBundleUrlString];


  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"Router"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [[UIViewController alloc] init];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
  // return [[FBSDKApplicationDelegate sharedInstance] application:application
  //                                 didFinishLaunchingWithOptions:launchOptions];
}

// // Facebook SDK
// - (void)applicationDidBecomeActive:(UIApplication *)application {
//   [FBSDKAppEvents activateApp];
// }

// - (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
//   return [[FBSDKApplicationDelegate sharedInstance] application:application
//                                                         openURL:url
//                                               sourceApplication:sourceApplication
//                                                      annotation:annotation];
// }

@end
